---
controller_execution_environments:

  - name: Image Mode EE
    organization: "Image Mode Lab"
    image: quay.io/philip860/image-mode:v2
    pull: always


  # - name: AAP Controller EE
  #   organization: "Image Mode Lab"
  #   image: quay.io/philip860/image-mode:v1
  #   pull: always