#!/usr/bin/env bash

###############################################################################
# RHTAS End-to-End Signing Validation
#
# Purpose:
#   Validate that a Red Hat Trusted Artifact Signer deployment can successfully
#   perform a complete keyless OCI artifact signing workflow.
#
# Validation flow:
#
#   RHTAS configuration
#       |
#       +--> HTTPS/TLS endpoint validation
#       |
#       +--> TUF trust metadata validation
#       |
#       +--> Cosign trust initialization
#       |
#       +--> Build disposable OCI image
#       |
#       +--> Push image to temporary registry
#       |
#       +--> Keycloak / OIDC authentication
#       |
#       +--> Fulcio certificate issuance
#       |
#       +--> Cosign signing
#       |
#       +--> Rekor transparency log
#       |
#       +--> Signature inspection
#       |
#       +--> Optional strict identity verification
#
# Requirements:
#   - /etc/profile.d/rhtas.sh generated by the RHTAS deployment
#   - cosign 3.x
#   - podman
#   - curl
#   - python3
#   - sha256sum
#
# Default RHTAS:
#   rhtas-1.lab.sandbox866.opentlc.com
#
# Default test registry:
#   ttl.sh
#
# Basic usage:
#
#   chmod +x test-rhtas-signing.sh
#   ./test-rhtas-signing.sh
#
# Override RHTAS host:
#
#   RHTAS_HOST=rhtas-1.example.com ./test-rhtas-signing.sh
#
# Optional strict identity verification:
#
#   SIGNING_IDENTITY=user@example.com ./test-rhtas-signing.sh
#
###############################################################################

set -Eeuo pipefail


###############################################################################
# Configuration
###############################################################################

RHTAS_HOST="${RHTAS_HOST:-rhtas-1.lab.sandbox866.opentlc.com}"
WORKDIR="${WORKDIR:-/tmp/rhtas-sign-test}"

CLI_SERVER_URL="https://cli-server.${RHTAS_HOST}"
FULCIO_URL="https://fulcio.${RHTAS_HOST}"
REKOR_URL="https://rekor.${RHTAS_HOST}"
TUF_URL="https://tuf.${RHTAS_HOST}"
TSA_URL="https://tsa.${RHTAS_HOST}"

TUF_ROOT="${WORKDIR}/1.root.json"


###############################################################################
# Formatting helpers
###############################################################################

section()
{
    echo
    echo "======================================================================"
    echo "$1"
    echo "======================================================================"
}


pass()
{
    echo "[PASS] $1"
}


warn()
{
    echo "[WARN] $1"
}


info()
{
    echo "[INFO] $1"
}


fail()
{
    echo "[FAIL] $1" >&2
    exit 1
}


###############################################################################
# Error handler
###############################################################################

error_handler()
{
    local rc=$?
    local line="${BASH_LINENO[0]:-unknown}"

    echo
    echo "======================================================================"
    echo "RHTAS SIGNING VALIDATION FAILED"
    echo "======================================================================"
    echo
    echo "Exit code: ${rc}"
    echo "Line:      ${line}"
    echo
    echo "Review the failure immediately above this message."
    echo

    exit "${rc}"
}

trap error_handler ERR


###############################################################################
# PHASE 1
# Load RHTAS configuration
###############################################################################

section "PHASE 1 - Load RHTAS configuration"


if [[ ! -f /etc/profile.d/rhtas.sh ]]; then
    fail "/etc/profile.d/rhtas.sh does not exist"
fi


# shellcheck disable=SC1091
source /etc/profile.d/rhtas.sh


pass "Loaded /etc/profile.d/rhtas.sh"


###############################################################################
# Use the explicitly selected RHTAS deployment.
###############################################################################

export RHTAS_HOST
export RHTAS_BASE_HOSTNAME="${RHTAS_HOST}"


CLI_SERVER_URL="https://cli-server.${RHTAS_HOST}"
FULCIO_URL="https://fulcio.${RHTAS_HOST}"
REKOR_URL="https://rekor.${RHTAS_HOST}"
TUF_URL="https://tuf.${RHTAS_HOST}"
TSA_URL="https://tsa.${RHTAS_HOST}"


###############################################################################
# Validate OIDC configuration supplied by the RHTAS profile.
###############################################################################

if [[ -z "${COSIGN_OIDC_CLIENT_ID:-}" ]]; then
    export COSIGN_OIDC_CLIENT_ID="trusted-artifact-signer"
fi


if [[ -z "${COSIGN_OIDC_ISSUER:-}" ]]; then
    fail "COSIGN_OIDC_ISSUER is not configured"
fi


if [[ -z "${COSIGN_OIDC_CLIENT_ID:-}" ]]; then
    fail "COSIGN_OIDC_CLIENT_ID is not configured"
fi


export COSIGN_YES="true"


echo
echo "RHTAS configuration:"
echo
echo "  RHTAS:       ${RHTAS_HOST}"
echo "  CLI Server:  ${CLI_SERVER_URL}"
echo "  Fulcio:      ${FULCIO_URL}"
echo "  Rekor:       ${REKOR_URL}"
echo "  TUF:         ${TUF_URL}"
echo "  TSA:         ${TSA_URL}"
echo "  OIDC issuer: ${COSIGN_OIDC_ISSUER}"
echo "  OIDC client: ${COSIGN_OIDC_CLIENT_ID}"


###############################################################################
# PHASE 2
# Validate required commands
###############################################################################

section "PHASE 2 - Verify required commands"


REQUIRED_COMMANDS=(
    curl
    cosign
    podman
    sha256sum
    python3
)


for cmd in "${REQUIRED_COMMANDS[@]}"; do

    if command -v "${cmd}" >/dev/null 2>&1; then
        pass "${cmd}: $(command -v "${cmd}")"
    else
        fail "Required command not found: ${cmd}"
    fi

done


###############################################################################
# Display Cosign version
###############################################################################

echo
cosign version
echo


COSIGN_VERSION="$(
    cosign version 2>/dev/null |
    awk '/GitVersion:/ {print $2}' |
    sed 's/^v//'
)"


if [[ -z "${COSIGN_VERSION}" ]]; then
    fail "Unable to determine Cosign version"
fi


COSIGN_MAJOR="${COSIGN_VERSION%%.*}"


if ! [[ "${COSIGN_MAJOR}" =~ ^[0-9]+$ ]]; then
    fail "Unable to determine Cosign major version"
fi


echo "Detected Cosign version: ${COSIGN_VERSION}"


if (( COSIGN_MAJOR < 3 )); then
    fail "Cosign 3.x or later is required for this validation"
fi


pass "Cosign version is compatible"


###############################################################################
# PHASE 3
# Validate HTTPS endpoints
###############################################################################

section "PHASE 3 - Verify RHTAS HTTPS endpoints"


check_endpoint()
{
    local name="$1"
    local url="$2"
    local expected_codes="$3"

    local code


    if ! code="$(
        curl \
            --silent \
            --show-error \
            --output /dev/null \
            --write-out '%{http_code}' \
            --max-time 15 \
            "${url}"
    )"; then

        fail "${name}: connection or TLS validation failed"

    fi


    echo "${name}: ${url} -> HTTP ${code}"


    case " ${expected_codes} " in

        *" ${code} "*)
            pass "${name}"
            ;;

        *)
            fail "${name}: unexpected HTTP ${code}"
            ;;

    esac
}


###############################################################################
# CLI Server
###############################################################################

check_endpoint \
    "CLI Server" \
    "${CLI_SERVER_URL}" \
    "200 301 302"


###############################################################################
# Fulcio
#
# HTTP 404 at / is acceptable. This phase validates DNS, TCP, TLS,
# nginx routing, and backend reachability.
###############################################################################

check_endpoint \
    "Fulcio" \
    "${FULCIO_URL}" \
    "200 404"


###############################################################################
# Rekor
###############################################################################

check_endpoint \
    "Rekor" \
    "${REKOR_URL}" \
    "200"


###############################################################################
# TUF
###############################################################################

check_endpoint \
    "TUF" \
    "${TUF_URL}/1.root.json" \
    "200"


###############################################################################
# TSA
#
# HTTP 404 at / is acceptable for the TSA service.
###############################################################################

check_endpoint \
    "TSA" \
    "${TSA_URL}" \
    "200 404"


###############################################################################
# PHASE 4
# Validate TUF trust root
###############################################################################

section "PHASE 4 - Validate TUF trust root"


mkdir -p "${WORKDIR}"

rm -f "${TUF_ROOT}"


curl \
    --fail \
    --silent \
    --show-error \
    "${TUF_URL}/1.root.json" \
    -o "${TUF_ROOT}"


python3 -m json.tool "${TUF_ROOT}" >/dev/null


pass "TUF root is valid JSON"


ROOT_CHECKSUM="$(
    sha256sum "${TUF_ROOT}" |
    awk '{print $1}'
)"


if [[ ! "${ROOT_CHECKSUM}" =~ ^[a-fA-F0-9]{64}$ ]]; then
    fail "Invalid SHA256 checksum generated for TUF root"
fi


echo
echo "TUF root:"
echo "  ${TUF_ROOT}"
echo
echo "SHA256:"
echo "  ${ROOT_CHECKSUM}"


###############################################################################
# PHASE 5
# Initialize Cosign trust
###############################################################################

section "PHASE 5 - Initialize Cosign trust"


cosign initialize \
    --mirror "${TUF_URL}" \
    --root "${TUF_URL}/1.root.json" \
    --root-checksum "${ROOT_CHECKSUM}"


pass "Cosign trust initialization completed"


###############################################################################
# PHASE 6
# Create disposable test image
###############################################################################

section "PHASE 6 - Create disposable test image"


cd "${WORKDIR}"


cat > Containerfile <<'EOF'
FROM scratch

LABEL org.opencontainers.image.title="RHTAS Signing Test"
LABEL org.opencontainers.image.description="Disposable OCI image used to validate Red Hat Trusted Artifact Signer"
LABEL org.opencontainers.image.vendor="Image Mode Lab"
EOF


pass "Created ${WORKDIR}/Containerfile"


###############################################################################
# Generate a unique disposable image.
#
# IMPORTANT:
#
# Do not inherit TEST_IMAGE from a previous shell invocation. Earlier versions
# allowed an exported TEST_IMAGE to survive between tests, which could result
# in malformed references such as:
#
#   repository@sha256@sha256:...
#
# Every validation run must use a fresh ttl.sh repository.
###############################################################################

unset TEST_IMAGE 2>/dev/null || true

TEST_ID="$(date +%s)-${RANDOM}"

TEST_REPOSITORY="ttl.sh/rhtas-test-${TEST_ID}"
TEST_IMAGE="${TEST_REPOSITORY}:1h"

export TEST_REPOSITORY
export TEST_IMAGE


echo
echo "Test image:"
echo "  ${TEST_IMAGE}"
echo


###############################################################################
# Build image
###############################################################################

podman build \
    --file Containerfile \
    --tag "${TEST_IMAGE}" \
    .


pass "Container image built successfully"


###############################################################################
# PHASE 7
# Push unsigned image
###############################################################################

section "PHASE 7 - Push unsigned test image"


podman push "${TEST_IMAGE}"


pass "Unsigned test image pushed successfully"


###############################################################################
# PHASE 8
# Resolve immutable image digest
###############################################################################

section "PHASE 8 - Resolve image digest"


IMAGE_DIGEST="$(
    podman inspect \
        --format '{{.Digest}}' \
        "${TEST_IMAGE}" \
        2>/dev/null || true
)"


if [[ -z "${IMAGE_DIGEST}" || "${IMAGE_DIGEST}" == "<none>" ]]; then
    fail "Unable to determine pushed image digest for ${TEST_IMAGE}"
fi


if [[ ! "${IMAGE_DIGEST}" =~ ^sha256:[a-fA-F0-9]{64}$ ]]; then
    fail "Invalid image digest returned by Podman: ${IMAGE_DIGEST}"
fi


SIGNED_IMAGE="${TEST_REPOSITORY}@${IMAGE_DIGEST}"


echo
echo "Tagged image:"
echo "  ${TEST_IMAGE}"
echo
echo "Digest:"
echo "  ${IMAGE_DIGEST}"
echo
echo "Signing reference:"
echo "  ${SIGNED_IMAGE}"


pass "Resolved image signing reference"


###############################################################################
# PHASE 9
# Sign image through RHTAS
###############################################################################

section "PHASE 9 - Sign image with RHTAS"


echo
echo "The next operation performs the RHTAS keyless signing test."
echo
echo "Signing services:"
echo
echo "  OIDC:    ${COSIGN_OIDC_ISSUER}"
echo "  Fulcio:  ${FULCIO_URL}"
echo "  Rekor:   ${REKOR_URL}"
echo
echo "Expected flow:"
echo
echo "  Cosign"
echo "     |"
echo "     +--> Keycloak / OIDC"
echo "     |"
echo "     +--> Fulcio certificate"
echo "     |"
echo "     +--> OCI signature"
echo "     |"
echo "     +--> Rekor transparency log"
echo
echo "HEADLESS / SSH USERS:"
echo
echo "  Cosign may display:"
echo
echo "    error opening browser"
echo
echo "  This is expected on a headless RHEL server."
echo
echo "  Cosign will then display a Keycloak authentication URL."
echo
echo "  1. Copy the complete URL."
echo "  2. Open it in a browser on your workstation."
echo "  3. Authenticate with your IdM/Keycloak account."
echo "  4. Copy the verification code."
echo "  5. Paste the code back into this terminal."
echo


###############################################################################
# IMPORTANT - Cosign 3 / RHTAS
#
# Disable Cosign's generated signing configuration for this operation.
#
# The RHTAS environment uses a custom Keycloak OIDC issuer. With generated
# Cosign signing configuration active, Cosign can reject explicitly configured
# signing services with:
#
#   cannot specify service URLs and use signing config
#
# Explicitly supplying the RHTAS services also proves that this deployment's
# Keycloak, Fulcio and Rekor instances are being tested.
###############################################################################

cosign sign \
    --yes \
    --use-signing-config=false \
    --fulcio-url="${FULCIO_URL}" \
    --rekor-url="${REKOR_URL}" \
    --oidc-issuer="${COSIGN_OIDC_ISSUER}" \
    --oidc-client-id="${COSIGN_OIDC_CLIENT_ID}" \
    "${SIGNED_IMAGE}"


pass "RHTAS keyless signing completed"


###############################################################################
# PHASE 10
# Inspect OCI signature
###############################################################################

section "PHASE 10 - Inspect OCI signature"


echo
echo "Inspecting signatures attached to:"
echo
echo "  ${SIGNED_IMAGE}"
echo


if cosign tree "${SIGNED_IMAGE}"; then

    pass "Cosign signature tree retrieved"

else

    warn "cosign tree did not return signature information"

fi


###############################################################################
# PHASE 11
# Download signature metadata
###############################################################################

section "PHASE 11 - Download signature metadata"


SIGNATURE_JSON="${WORKDIR}/signature.json"

rm -f "${SIGNATURE_JSON}"


if cosign download signature "${SIGNED_IMAGE}" > "${SIGNATURE_JSON}"; then

    if [[ -s "${SIGNATURE_JSON}" ]]; then

        pass "Downloaded OCI signature metadata"

        echo
        echo "Signature metadata:"
        echo

        if python3 -m json.tool "${SIGNATURE_JSON}" 2>/dev/null; then
            :
        else
            cat "${SIGNATURE_JSON}"
        fi

    else

        warn "Cosign returned an empty signature metadata file"

    fi

else

    warn "Unable to download signature metadata"

fi


###############################################################################
# PHASE 12
# Strict identity verification
#
# Keyless verification should verify BOTH:
#
#   1. Expected certificate identity
#   2. Expected OIDC issuer
#
# Supply the expected identity with:
#
#   SIGNING_IDENTITY=user@example.com ./test-rhtas-signing.sh
###############################################################################

section "PHASE 12 - Verify signed artifact"


IDENTITY_VERIFICATION="SKIPPED"


if [[ -n "${SIGNING_IDENTITY:-}" ]]; then

    echo
    echo "Expected certificate identity:"
    echo "  ${SIGNING_IDENTITY}"
    echo
    echo "Expected OIDC issuer:"
    echo "  ${COSIGN_OIDC_ISSUER}"
    echo


    ###########################################################################
    # Verification explicitly disables generated signing configuration so the
    # verification remains tied to the selected RHTAS deployment.
    ###########################################################################

    cosign verify \
        --use-signing-config=false \
        --rekor-url="${REKOR_URL}" \
        --certificate-identity="${SIGNING_IDENTITY}" \
        --certificate-oidc-issuer="${COSIGN_OIDC_ISSUER}" \
        "${SIGNED_IMAGE}"


    pass "Certificate identity and artifact signature verified"

    IDENTITY_VERIFICATION="PASS"

else

    warn "SIGNING_IDENTITY was not supplied."

    echo
    echo "The artifact was successfully signed."
    echo
    echo "Strict identity verification requires the expected identity from"
    echo "the Fulcio signing certificate."
    echo
    echo "To perform strict verification, run:"
    echo
    echo "  SIGNING_IDENTITY=<identity> $0"
    echo
    echo "Example:"
    echo
    echo "  SIGNING_IDENTITY=user01@example.com $0"
    echo

fi


###############################################################################
# PHASE 13
# Final validation summary
###############################################################################

section "PHASE 13 - Validation summary"


echo
echo "RHTAS deployment:"
echo "  ${RHTAS_HOST}"
echo
echo "Test image:"
echo "  ${TEST_IMAGE}"
echo
echo "Signing reference:"
echo "  ${SIGNED_IMAGE}"
echo
echo "OIDC issuer:"
echo "  ${COSIGN_OIDC_ISSUER}"
echo
echo "OIDC client:"
echo "  ${COSIGN_OIDC_CLIENT_ID}"
echo


echo "Validation results:"
echo
echo "  [PASS] RHTAS configuration loaded"
echo "  [PASS] Required client commands"
echo "  [PASS] Cosign 3.x"
echo "  [PASS] RHTAS HTTPS/TLS"
echo "  [PASS] CLI Server connectivity"
echo "  [PASS] Fulcio connectivity"
echo "  [PASS] Rekor connectivity"
echo "  [PASS] TUF trust repository"
echo "  [PASS] TSA connectivity"
echo "  [PASS] TUF root validation"
echo "  [PASS] Cosign trust initialization"
echo "  [PASS] OCI test image build"
echo "  [PASS] OCI registry push"
echo "  [PASS] RHTAS keyless signing"
echo "  [PASS] Fulcio signing workflow"
echo "  [PASS] Rekor transparency logging"
echo "  [PASS] OCI signature storage"
echo "  [PASS] RHTAS signing workflow"


if [[ "${IDENTITY_VERIFICATION}" == "PASS" ]]; then

    echo "  [PASS] Certificate identity verification"

else

    echo "  [SKIP] Certificate identity verification"

fi


echo
echo "======================================================================"
echo "RHTAS SIGNING VALIDATION COMPLETED SUCCESSFULLY"
echo "======================================================================"
echo
echo "Artifact:"
echo
echo "  ${SIGNED_IMAGE}"
echo


if [[ "${IDENTITY_VERIFICATION}" != "PASS" ]]; then

    echo "NOTE:"
    echo
    echo "  Artifact signing succeeded."
    echo
    echo "  Strict certificate identity verification was skipped because"
    echo "  SIGNING_IDENTITY was not provided."
    echo

fi


###############################################################################
# End
###############################################################################

exit 0