############################################################
# Server Information
############################################################

output "servers" {
  description = "Created lab servers with hostname, role, private IP, optional persistent Elastic IP, FQDN, instance profile, and optional SSH command."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = instance.tags.Name
      fqdn       = local.flattened_servers[name].hostname
      role       = instance.tags.Role
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      instance_profile = (
        local.flattened_servers[name].role == "aap"
        ? aws_iam_instance_profile.aap.name
        : local.flattened_servers[name].role == "satellite"
        ? aws_iam_instance_profile.satellite.name
        : local.flattened_servers[name].role == "gitlab"
        ? aws_iam_instance_profile.gitlab_runtime.name
        : local.flattened_servers[name].role == "image-builder"
        ? aws_iam_instance_profile.image_builder.name
        : aws_iam_instance_profile.lab_ec2_default.name
      )

      ssh = try(
        "ssh -i ${local.ansible_ssh_private_key_file} ec2-user@${aws_eip.server[name].public_ip}",
        ""
      )
    }
  }
}

############################################################
# Generated SSH Key Information
############################################################

output "lab_ssh_key_pair_name" {
  description = "AWS EC2 key pair name generated by Terraform."
  value       = aws_key_pair.lab.key_name
}

output "lab_ssh_private_key_file" {
  description = "Local sensitive private key file used by Terraform local-exec and Ansible."
  value       = local.ansible_ssh_private_key_file
}

output "lab_ssh_private_key_secret_name" {
  description = "AWS Secrets Manager secret name containing the generated lab SSH private key."
  value       = local.lab_ssh_private_key_secret_name
}

############################################################
# Generated Ansible Inventory
############################################################

output "ansible_inventory" {
  description = "Dynamic Ansible inventory generated from Terraform-created AWS servers."

  value = templatefile("${path.module}/inventory.tpl", {
    aws_dns_resolver             = local.aws_dns_resolver
    ansible_ssh_private_key_file = local.ansible_ssh_private_key_file

    aws_region    = var.aws_region
    aws_profile   = var.aws_profile
    secret_prefix = var.secret_prefix

    lab_ssh_private_key_secret_name = (
      local.lab_ssh_private_key_secret_name
    )

    satellite_iso_s3_bucket = (
      var.satellite_iso_s3_bucket
    )

    satellite_iso_s3_key = (
      var.satellite_iso_s3_key
    )

    satellite_iso_sha256 = (
      var.satellite_iso_sha256
    )

    satellite_manifest_s3_bucket = (
      var.satellite_manifest_s3_bucket
    )

    satellite_manifest_s3_key = (
      var.satellite_manifest_s3_key
    )

    satellite_manifest_sha256 = (
      var.satellite_manifest_sha256
    )

    satellite_initial_admin_username = (
      var.satellite_initial_admin_username
    )

    satellite_organization_name = (
      var.satellite_organization_name
    )

    satellite_location_name = (
      var.satellite_location_name
    )

    satellite_compute_resource_name = (
      var.satellite_compute_resource_name
    )

    satellite_compute_profile_name = (
      var.satellite_compute_profile_name
    )

    satellite_default_compute_profile_name = (
      var.satellite_default_compute_profile_name
    )

    satellite_gitlab_compute_profile_name = (
      var.satellite_gitlab_compute_profile_name
    )

    satellite_image_builder_compute_profile_name = (
      var.satellite_image_builder_compute_profile_name
    )

    satellite_compute_region = (
      var.aws_region
    )

    satellite_compute_availability_zone = (
      aws_subnet.public.availability_zone
    )

    satellite_compute_subnet_id = (
      aws_subnet.public.id
    )

    satellite_compute_vpc_id = (
      aws_vpc.lab.id
    )

    satellite_compute_security_group_ids = [
      aws_security_group.lab.id,
      aws_security_group.gitlab.id
    ]

    satellite_image_builder_security_group_ids = [
      aws_security_group.lab.id,
      aws_security_group.image_builder.id
    ]

    satellite_default_security_group_ids = [
      aws_security_group.lab.id
    ]

    satellite_compute_key_pair = (
      aws_key_pair.lab.key_name
    )

    satellite_default_instance_profile = (
      aws_iam_instance_profile.lab_ec2_default.name
    )

    satellite_gitlab_instance_profile = (
      aws_iam_instance_profile.gitlab_runtime.name
    )

    satellite_image_builder_instance_profile = (
      aws_iam_instance_profile.image_builder.name
    )

    satellite_aws_access_key_secret_name = (
      aws_secretsmanager_secret.satellite_aws_access_key_id.name
    )

    satellite_aws_secret_key_secret_name = (
      aws_secretsmanager_secret.satellite_aws_secret_access_key.name
    )

    gitlab_registry_port = (
      var.gitlab_registry_port
    )

    image_builder_cockpit_port = (
      var.image_builder_cockpit_port
    )

    image_mode_artifact_bucket = (
      aws_s3_bucket.image_mode_artifacts.id
    )

    rhel_iam_credentials_secret_name = (
      aws_secretsmanager_secret.rhel_iam_credentials.name
    )

    vmimport_role_name = (
      aws_iam_role.vmimport.name
    )

    lab_users = var.lab_users
    idm_users = var.idm_users

    parent_domain_name = local.parent_domain_name
    idm_domain_name    = local.idm_domain_name
    idm_realm_name     = local.idm_realm_name
    idm_server_fqdn    = local.primary_idm_hostname
    idm_server_ip      = local.primary_idm_private_ip

    servers = {
      for name, instance in aws_instance.server :
      name => {
        hostname   = instance.tags.Name
        fqdn       = local.flattened_servers[name].hostname
        role       = instance.tags.Role
        private_ip = instance.private_ip

        public_ip = coalesce(
          try(aws_eip.server[name].public_ip, null),
          instance.public_ip,
          ""
        )

        ansible_host = coalesce(
          try(aws_eip.server[name].public_ip, null),
          instance.public_ip,
          instance.private_ip
        )

        iam_instance_profile = (
          local.flattened_servers[name].role == "aap"
          ? aws_iam_instance_profile.aap.name
          : local.flattened_servers[name].role == "satellite"
          ? aws_iam_instance_profile.satellite.name
          : local.flattened_servers[name].role == "gitlab"
          ? aws_iam_instance_profile.gitlab_runtime.name
          : local.flattened_servers[name].role == "image-builder"
          ? aws_iam_instance_profile.image_builder.name
          : aws_iam_instance_profile.lab_ec2_default.name
        )

        acm_certificate_arn = try(
          aws_acm_certificate.server[name].arn,
          ""
        )
      }
    }
  })
}

############################################################
# AWS Network Information
############################################################

output "vpc_id" {
  description = "Created VPC ID."
  value       = aws_vpc.lab.id
}

output "vpc_cidr" {
  description = "Created VPC CIDR block."
  value       = aws_vpc.lab.cidr_block
}

output "aws_dns_resolver" {
  description = "AWS VPC DNS resolver address, normally the VPC CIDR base address plus 2."
  value       = local.aws_dns_resolver
}

output "public_subnet_id" {
  description = "Created main lab subnet ID."
  value       = aws_subnet.public.id
}

output "public_subnet_availability_zone" {
  description = "Availability Zone containing the main lab subnet."
  value       = aws_subnet.public.availability_zone
}

output "resolver_subnet_id" {
  description = "Second subnet ID used by the Route53 Resolver outbound endpoint."
  value       = aws_subnet.resolver.id
}

output "security_group_id" {
  description = "Common lab security group ID."
  value       = aws_security_group.lab.id
}

output "image_builder_security_group_id" {
  description = "Additional security group used by Image Builder hosts."
  value       = aws_security_group.image_builder.id
}

output "gitlab_security_group_id" {
  description = "Additional security group used by GitLab hosts."
  value       = aws_security_group.gitlab.id
}

############################################################
# DNS Information
############################################################

output "parent_domain_name" {
  description = "Effective OpenTLC parent DNS domain discovered or provided for this lab."
  value       = local.parent_domain_name
}

output "idm_domain_name" {
  description = "IdM-managed DNS domain."
  value       = local.idm_domain_name
}

output "idm_realm_name" {
  description = "IdM Kerberos realm name."
  value       = local.idm_realm_name
}

output "public_dns_zone_id" {
  description = "Public Route53 hosted zone ID used for public DNS records."
  value       = local.public_route53_zone_id
}

output "route53_resolver_endpoint_id" {
  description = "Route53 Resolver outbound endpoint ID used to forward IdM DNS queries."
  value       = aws_route53_resolver_endpoint.outbound.id
}

output "route53_resolver_rule_id" {
  description = "Route53 Resolver rule ID forwarding the IdM DNS zone to the IdM server."
  value       = aws_route53_resolver_rule.idm_forward.id
}

output "route53_resolver_forward_domain" {
  description = "DNS domain forwarded from AWS Resolver to IdM DNS."
  value       = local.idm_domain_name
}

output "route53_resolver_forward_target" {
  description = "Private IP of the selected primary IdM DNS server used as the Route53 Resolver forwarding target."
  value       = local.primary_idm_private_ip
}

output "server_fqdns" {
  description = "FQDNs created for lab servers."

  value = {
    for name, server in local.flattened_servers :
    name => server.hostname
  }
}

############################################################
# Role-Based Server Information
############################################################

output "idm_servers" {
  description = "Created IdM servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      url              = "https://${local.flattened_servers[name].hostname}"
      instance_profile = aws_iam_instance_profile.lab_ec2_default.name
    }
    if local.flattened_servers[name].role == "idm"
  }
}

output "aap_servers" {
  description = "Created AAP servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      url              = "https://${local.flattened_servers[name].hostname}"
      instance_profile = aws_iam_instance_profile.aap.name
    }
    if local.flattened_servers[name].role == "aap"
  }
}

output "quay_servers" {
  description = "Created Quay servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      url              = "https://${local.flattened_servers[name].hostname}"
      instance_profile = aws_iam_instance_profile.lab_ec2_default.name
    }
    if local.flattened_servers[name].role == "quay"
  }
}

output "satellite_servers" {
  description = "Created Satellite servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      url              = "https://${local.flattened_servers[name].hostname}"
      instance_profile = aws_iam_instance_profile.satellite.name
    }
    if local.flattened_servers[name].role == "satellite"
  }
}

output "image_builder_servers" {
  description = "Created Image Builder servers. Public IP is blank when an Image Builder host is not included in public_server_names."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      url = "https://${local.flattened_servers[name].hostname}:${var.image_builder_cockpit_port}"

      instance_profile = aws_iam_instance_profile.image_builder.name
    }
    if local.flattened_servers[name].role == "image-builder"
  }
}

output "gitlab_servers" {
  description = "Created GitLab servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip

      public_ip = try(
        aws_eip.server[name].public_ip,
        ""
      )

      url = "${var.gitlab_external_url_scheme}://${local.flattened_servers[name].hostname}"

      registry_url = "${local.flattened_servers[name].hostname}:${var.gitlab_registry_port}"

      instance_profile = aws_iam_instance_profile.gitlab_runtime.name
    }
    if local.flattened_servers[name].role == "gitlab"
  }
}

############################################################
# Primary Service Endpoints
############################################################

output "primary_idm_fqdn" {
  description = "Primary IdM server FQDN selected dynamically."
  value       = local.primary_idm_hostname
}

output "primary_idm_private_ip" {
  description = "Primary IdM server private IP selected dynamically."
  value       = local.primary_idm_private_ip
}

output "aap_urls" {
  description = "AAP URLs."

  value = {
    for name, server in local.flattened_servers :
    name => "https://${server.hostname}"
    if server.role == "aap"
  }
}

output "quay_urls" {
  description = "Quay URLs."

  value = {
    for name, server in local.flattened_servers :
    name => "https://${server.hostname}"
    if server.role == "quay"
  }
}

output "satellite_urls" {
  description = "Satellite URLs."

  value = {
    for name, server in local.flattened_servers :
    name => "https://${server.hostname}"
    if server.role == "satellite"
  }
}

output "image_builder_fqdns" {
  description = "Image Builder FQDNs."

  value = {
    for name, server in local.flattened_servers :
    name => server.hostname
    if server.role == "image-builder"
  }
}

output "image_builder_urls" {
  description = "Image Builder Cockpit URLs."

  value = {
    for name, server in local.flattened_servers :
    name => (
      "https://${server.hostname}:${var.image_builder_cockpit_port}"
    )
    if server.role == "image-builder"
  }
}

output "gitlab_urls" {
  description = "GitLab web URLs."

  value = {
    for name, server in local.flattened_servers :
    name => (
      "${var.gitlab_external_url_scheme}://${server.hostname}"
    )
    if server.role == "gitlab"
  }
}

output "gitlab_registry_urls" {
  description = "GitLab container registry endpoints."

  value = {
    for name, server in local.flattened_servers :
    name => "${server.hostname}:${var.gitlab_registry_port}"
    if server.role == "gitlab"
  }
}

############################################################
# Quay IdM LDAP Information
############################################################

output "quay_idm_ldap_settings" {
  description = "Derived IdM LDAP settings used by Quay."

  value = {
    ldap_uri = "ldap://${local.primary_idm_hostname}:389"

    ldap_base_dn = join(
      ",",
      [
        for part in split(".", local.idm_domain_name) :
        "dc=${part}"
      ]
    )

    ldap_bind_user = (
      "uid=admin,cn=users,cn=accounts,${join(",", [
        for part in split(".", local.idm_domain_name) :
        "dc=${part}"
      ])}"
    )

    admin_users = var.idm_users
  }
}

############################################################
# GitLab IdM LDAP Information
############################################################

output "gitlab_idm_ldap_settings" {
  description = "Derived IdM LDAP settings available to the GitLab deployment."

  value = {
    ldap_host = local.primary_idm_hostname
    ldap_port = 636
    ldap_uri  = "ldaps://${local.primary_idm_hostname}:636"

    ldap_base_dn = join(
      ",",
      [
        for part in split(".", local.idm_domain_name) :
        "dc=${part}"
      ]
    )

    ldap_bind_user = (
      "uid=admin,cn=users,cn=accounts,${join(",", [
        for part in split(".", local.idm_domain_name) :
        "dc=${part}"
      ])}"
    )

    admin_users = var.idm_users
  }
}

############################################################
# AWS Secrets Manager Secret Names
############################################################

output "quay_secret_names" {
  description = "AWS Secrets Manager secret names used by the Quay deployment."

  value = {
    db_password        = "${var.secret_prefix}/quay/db_password"
    secret_key         = "${var.secret_prefix}/quay/secret_key"
    database_secret    = "${var.secret_prefix}/quay/database_secret_key"
    redis_password     = "${var.secret_prefix}/quay/redis_password"
    superuser          = "${var.secret_prefix}/quay/superuser"
    superuser_password = "${var.secret_prefix}/quay/superuser_password"
    admin_access_token = "${var.secret_prefix}/quay/admin_access_token"
    registry_username  = "${var.secret_prefix}/redhat/registry_username"
    registry_password  = "${var.secret_prefix}/redhat/registry_password"
    idm_admin_password = "${var.secret_prefix}/idm/admin_password"
  }
}

output "gitlab_secret_names" {
  description = "AWS Secrets Manager secret names used by the GitLab deployment."

  value = {
    root_username = (
      "${var.secret_prefix}/gitlab/root_username"
    )

    root_password = (
      "${var.secret_prefix}/gitlab/root_password"
    )

    postgresql_password = (
      "${var.secret_prefix}/gitlab/postgresql_password"
    )

    redis_password = (
      "${var.secret_prefix}/gitlab/redis_password"
    )

    runner_registration_token = (
      "${var.secret_prefix}/gitlab/runner_registration_token"
    )

    initial_shared_runner_token = (
      "${var.secret_prefix}/gitlab/initial_shared_runner_token"
    )

    rails_secret = (
      "${var.secret_prefix}/gitlab/rails_secret"
    )

    otp_key_base = (
      "${var.secret_prefix}/gitlab/otp_key_base"
    )

    db_key_base = (
      "${var.secret_prefix}/gitlab/db_key_base"
    )

    openid_client_secret = (
      "${var.secret_prefix}/gitlab/openid_connect_client_secret"
    )

    idm_admin_password = (
      "${var.secret_prefix}/idm/admin_password"
    )
  }
}

output "image_mode_aws_secret_names" {
  description = "Secrets Manager secret names used by the Image Mode AWS automation workflow."

  value = {
    rhel_iam_credentials = (
      aws_secretsmanager_secret.rhel_iam_credentials.name
    )

    satellite_access_key = (
      aws_secretsmanager_secret.satellite_aws_access_key_id.name
    )

    satellite_secret_key = (
      aws_secretsmanager_secret.satellite_aws_secret_access_key.name
    )

    ssh_private_key = (
      aws_secretsmanager_secret.ssh_private_key.name
    )
  }
}

############################################################
# Useful Connection Summary
############################################################

output "ssh_commands" {
  description = "Quick SSH commands for instances included in public_server_names and assigned Elastic IPs."

  value = {
    for name, eip in aws_eip.server :
    name => (
      "ssh -i ${local.ansible_ssh_private_key_file} ec2-user@${eip.public_ip}"
    )
  }
}

############################################################
# Satellite Installation Information
############################################################

output "satellite_iso_s3_uri" {
  description = "S3 URI of the Satellite installation ISO."

  value = (
    "s3://${var.satellite_iso_s3_bucket}/${var.satellite_iso_s3_key}"
  )
}

output "satellite_iso_s3_object_arn" {
  description = "S3 object ARN permitted by the Satellite EC2 IAM role."

  value = (
    "arn:aws:s3:::${var.satellite_iso_s3_bucket}/${var.satellite_iso_s3_key}"
  )
}

output "satellite_manifest_s3_uri" {
  description = "S3 URI of the Satellite subscription manifest."

  value = (
    "s3://${var.satellite_manifest_s3_bucket}/${var.satellite_manifest_s3_key}"
  )
}

output "satellite_admin_password_secret_name" {
  description = "AWS Secrets Manager secret containing the Satellite administrator password."
  value       = "${var.secret_prefix}/satellite/admin_password"
}

output "satellite_iam_role_name" {
  description = "IAM role used by the Satellite EC2 instance."
  value       = aws_iam_role.satellite.name
}

output "satellite_iam_role_arn" {
  description = "ARN of the IAM role used by the Satellite EC2 instance."
  value       = aws_iam_role.satellite.arn
}

output "satellite_iam_instance_profile_name" {
  description = "IAM instance profile used by the Satellite EC2 instance."
  value       = aws_iam_instance_profile.satellite.name
}

output "satellite_iam_instance_profile_arn" {
  description = "ARN of the IAM instance profile used by the Satellite EC2 instance."
  value       = aws_iam_instance_profile.satellite.arn
}

output "satellite_installation_settings" {
  description = "Non-sensitive Satellite installation settings."

  value = {
    iso_s3_uri = (
      "s3://${var.satellite_iso_s3_bucket}/${var.satellite_iso_s3_key}"
    )

    manifest_s3_uri = (
      "s3://${var.satellite_manifest_s3_bucket}/${var.satellite_manifest_s3_key}"
    )

    admin_user    = var.satellite_initial_admin_username
    organization  = var.satellite_organization_name
    location      = var.satellite_location_name
    password_path = "${var.secret_prefix}/satellite/admin_password"
  }
}

############################################################
# Satellite AWS Compute Resource Information
############################################################

output "satellite_compute_resource" {
  description = "AWS details used to configure the Satellite EC2 Compute Resource and role-specific compute profiles."

  value = {
    name = (
      var.satellite_compute_resource_name
    )

    compute_profile = (
      var.satellite_compute_profile_name
    )

    default_compute_profile = (
      var.satellite_default_compute_profile_name
    )

    gitlab_compute_profile = (
      var.satellite_gitlab_compute_profile_name
    )

    image_builder_compute_profile = (
      var.satellite_image_builder_compute_profile_name
    )

    region            = var.aws_region
    availability_zone = aws_subnet.public.availability_zone
    vpc_id            = aws_vpc.lab.id
    subnet_id         = aws_subnet.public.id
    key_pair          = aws_key_pair.lab.key_name

    common_security_group_id = (
      aws_security_group.lab.id
    )

    gitlab_security_group_id = (
      aws_security_group.gitlab.id
    )

    image_builder_security_group_id = (
      aws_security_group.image_builder.id
    )

    default_instance_profile = (
      aws_iam_instance_profile.lab_ec2_default.name
    )

    gitlab_instance_profile = (
      aws_iam_instance_profile.gitlab_runtime.name
    )

    image_builder_instance_profile = (
      aws_iam_instance_profile.image_builder.name
    )

    access_key_secret_name = (
      aws_secretsmanager_secret.satellite_aws_access_key_id.name
    )

    secret_key_secret_name = (
      aws_secretsmanager_secret.satellite_aws_secret_access_key.name
    )
  }
}

output "satellite_provisioner_iam_user_name" {
  description = "IAM user used by Satellite to provision EC2 instances."
  value       = aws_iam_user.satellite_provisioner.name
}

output "satellite_provisioner_iam_user_arn" {
  description = "ARN of the IAM user used by Satellite to provision EC2 instances."
  value       = aws_iam_user.satellite_provisioner.arn
}

output "satellite_provisioner_access_key_id" {
  description = "Access-key ID used by the Satellite EC2 Compute Resource. The secret access key is not exposed."
  value       = aws_iam_access_key.satellite_provisioner.id
  sensitive   = true
}

output "satellite_aws_access_key_secret_name" {
  description = "Secrets Manager secret containing the Satellite AWS access-key ID."
  value       = aws_secretsmanager_secret.satellite_aws_access_key_id.name
}

output "satellite_aws_secret_access_key_secret_name" {
  description = "Secrets Manager secret containing the Satellite AWS secret access key."
  value       = aws_secretsmanager_secret.satellite_aws_secret_access_key.name
}

############################################################
# AAP IAM Information
############################################################

output "aap_iam_role_name" {
  description = "IAM role used by the AAP EC2 instance."
  value       = aws_iam_role.aap.name
}

output "aap_iam_role_arn" {
  description = "ARN of the IAM role used by the AAP EC2 instance."
  value       = aws_iam_role.aap.arn
}

output "aap_iam_instance_profile_name" {
  description = "IAM instance profile assigned to AAP EC2 instances."
  value       = aws_iam_instance_profile.aap.name
}

output "aap_iam_instance_profile_arn" {
  description = "ARN of the IAM instance profile assigned to AAP EC2 instances."
  value       = aws_iam_instance_profile.aap.arn
}

############################################################
# GitLab Runtime IAM Information
############################################################

output "gitlab_iam_role_name" {
  description = "IAM role used by Terraform-created and Satellite-created GitLab EC2 instances."
  value       = aws_iam_role.gitlab_runtime.name
}

output "gitlab_iam_role_arn" {
  description = "ARN of the GitLab runtime IAM role."
  value       = aws_iam_role.gitlab_runtime.arn
}

output "gitlab_iam_instance_profile_name" {
  description = "IAM instance profile assigned to GitLab EC2 instances."
  value       = aws_iam_instance_profile.gitlab_runtime.name
}

output "gitlab_iam_instance_profile_arn" {
  description = "ARN of the IAM instance profile assigned to GitLab EC2 instances."
  value       = aws_iam_instance_profile.gitlab_runtime.arn
}

############################################################
# Default Lab EC2 IAM Information
############################################################

output "lab_default_iam_role_name" {
  description = "Default IAM role assigned to generic Image Mode lab EC2 instances."
  value       = aws_iam_role.lab_ec2_default.name
}

output "lab_default_iam_role_arn" {
  description = "ARN of the default Image Mode lab EC2 IAM role."
  value       = aws_iam_role.lab_ec2_default.arn
}

output "lab_default_instance_profile_name" {
  description = "Default instance profile assigned to generic Image Mode lab EC2 instances."
  value       = aws_iam_instance_profile.lab_ec2_default.name
}

output "lab_default_instance_profile_arn" {
  description = "ARN of the default Image Mode lab EC2 instance profile."
  value       = aws_iam_instance_profile.lab_ec2_default.arn
}

############################################################
# Image Builder IAM Information
############################################################

output "image_builder_iam_role_name" {
  description = "IAM role assigned to Image Builder EC2 instances."
  value       = aws_iam_role.image_builder.name
}

output "image_builder_iam_role_arn" {
  description = "ARN of the IAM role assigned to Image Builder EC2 instances."
  value       = aws_iam_role.image_builder.arn
}

output "image_builder_instance_profile_name" {
  description = "Instance profile assigned to Image Builder hosts."
  value       = aws_iam_instance_profile.image_builder.name
}

output "image_builder_instance_profile_arn" {
  description = "ARN of the instance profile assigned to Image Builder hosts."
  value       = aws_iam_instance_profile.image_builder.arn
}

############################################################
# Image Mode Artifact Bucket
############################################################

output "image_mode_artifact_bucket_name" {
  description = "Shared S3 bucket for Image Mode build artifacts and VM import staging."
  value       = aws_s3_bucket.image_mode_artifacts.id
}

output "image_mode_artifact_bucket_arn" {
  description = "ARN of the shared Image Mode artifact bucket."
  value       = aws_s3_bucket.image_mode_artifacts.arn
}

output "image_mode_artifact_bucket_uri" {
  description = "S3 URI of the shared Image Mode artifact bucket."
  value       = "s3://${aws_s3_bucket.image_mode_artifacts.id}"
}

output "image_mode_artifact_policy_name" {
  description = "Customer-managed IAM policy granting access to the Image Mode artifact bucket."
  value       = aws_iam_policy.image_mode_artifact_bucket_rw.name
}

output "image_mode_artifact_policy_arn" {
  description = "ARN of the customer-managed IAM policy granting access to the Image Mode artifact bucket."
  value       = aws_iam_policy.image_mode_artifact_bucket_rw.arn
}

############################################################
# Bootc AMI Import IAM Information
############################################################

output "bootc_ami_import_policy_name" {
  description = "Customer-managed IAM policy used to initiate bootc image imports."
  value       = aws_iam_policy.bootc_ami_import_caller.name
}

output "bootc_ami_import_policy_arn" {
  description = "ARN of the customer-managed IAM policy used to initiate bootc image imports."
  value       = aws_iam_policy.bootc_ami_import_caller.arn
}

output "vmimport_role_name" {
  description = "AWS VM Import/Export service role."
  value       = aws_iam_role.vmimport.name
}

output "vmimport_role_arn" {
  description = "ARN of the AWS VM Import/Export service role."
  value       = aws_iam_role.vmimport.arn
}

############################################################
# rhel-iam Automation User
############################################################

output "rhel_iam_user_name" {
  description = "Image Mode automation IAM username."
  value       = aws_iam_user.rhel_iam.name
}

output "rhel_iam_user_arn" {
  description = "ARN of the Image Mode automation IAM user."
  value       = aws_iam_user.rhel_iam.arn
}

output "rhel_iam_credentials_secret_name" {
  description = "Secrets Manager secret containing rhel-iam access credentials."
  value       = aws_secretsmanager_secret.rhel_iam_credentials.name
}

output "rhel_iam_credentials_secret_arn" {
  description = "ARN of the Secrets Manager secret containing rhel-iam access credentials."
  value       = aws_secretsmanager_secret.rhel_iam_credentials.arn
}