---
- name: Deploy GitLab with ACM TLS and Red Hat IdM authentication
  hosts: gitlab
  become: true
  gather_facts: true
  any_errors_fatal: true
  serial: 1

  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    AWS_DEFAULT_REGION: "{{ aws_region }}"

  roles:
    - role: deploy_gitlab
    - role: gitlab_content_bootstrap
    - role: gitlab_group_visibility
